workflows:
  ios-build:
    name: Build iOS from PWABuilder
    environment:
      xcode: latest
    scripts:
      - name: List available schemes
        script: |
          xcodebuild -list -project "Digi Calculator.xcodeproj"

      - name: Build iOS App
        script: |
          xcodebuild -project "Digi Calculator.xcodeproj" \
            -scheme "Digi Calculator" \
            -sdk iphoneos \
            -configuration Release \
            build

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
