workflows:
  ios-build:
    name: Build iOS for Simulator (no signing)
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods (jika perlu)
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Tidak ada Podfile, lewati install pod."
          fi

      - name: List Schemes
        script: |
          xcodebuild -list -project "Digi Calculator.xcodeproj"

      - name: Build App for iOS Simulator
        script: |
          xcodebuild -project "Digi Calculator.xcodeproj" \
            -scheme "Digi Calculator" \
            -sdk iphonesimulator \
            -configuration Debug \
            build

    artifacts:
      - build/**/*.app
