workflows:
  ios-build:
    name: Build iOS from PWABuilder
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install || echo "No Podfile found, skipping"

      - name: List available schemes
        script: |
          xcodebuild -list -project "Digi Calculator.xcodeproj"

      - name: Build iOS App for Simulator (no signing)
        script: |
          xcodebuild -project "Digi Calculator.xcodeproj" \
            -scheme "Digi Calculator" \
            -sdk iphonesimulator \
            -configuration Debug \
            build

    artifacts:
      - build/**/*.app

    code_signing:
      distribution_cert: null
      provisioning_profile: null
