workflows:
  ios-build:
    name: Build iOS for Simulator (no signing)
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods (jika perlu)
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Tidak ada Podfile, lewati install pod."
          fi

      - name: List Schemes
        script: |
          xcodebuild -list -workspace "Digi Calculator.xcworkspace"

      - name: Build App for iOS Simulator
        script: |
          xcodebuild -workspace "Digi Calculator.xcworkspace" \
            -scheme "Digi Calculator" \
            -sdk iphonesimulator \
            -configuration Debug \
            build

      - name: Find .app files
        script: |
          find $PWD -name "*.app" -print

    artifacts:
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
