workflows:
  ios-build:
    name: Build iOS App
    environment:
      xcode: latest
    scripts:
      - name: List available Xcode schemes
        script: |
          xcodebuild -list -project "Digi Calculator.xcodeproj"

      - name: Build iOS App
        script: |
          xcodebuild -project "Digi Calculator.xcodeproj" \
            -scheme "Digi Calculator" \
            -sdk iphoneos \
            -configuration Release \
            build

    artifacts:
      - build/ios/Release-iphoneos/*.app
      - build/ios/Release-iphoneos/*.ipa
