workflows:
  ios-build:
    name: Build iOS from PWABuilder
    environment:
      xcode: latest
    scripts:
      - name: Cari file xcodeproj
        script: |
          echo "Daftar file .xcodeproj:"
          find . -name "*.xcodeproj"

      - name: List available schemes
        script: |
          xcodebuild -list -project "$(find . -name "*.xcodeproj" | head -n 1)"

      - name: Build iOS App
        script: |
          PROJECT=$(find . -name "*.xcodeproj" | head -n 1)
          SCHEME="Digi Calculator" # ubah ini jika berbeda
          xcodebuild -project "$PROJECT" \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            build

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
